version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PASSWORD=password
    ports:
      - 8080:5000
    volumes:
      - head-detect-annotator:/var/www/data
    restart: always

volumes:
  head-detect-annotator:
